public class Constants {
	public static Final integer DEFAULT_ROWS = 5;
    public static Final String SELECT_ONE = Label.SELECT_ONE;
    public static Final String INVENTORY_LEVEL_LOW = Label.INVENTORY_LEVEL_LOW;
    public static Final List<Schema.PicklistEntry> PRODUCT_FAMILY = Product2.Family.getDescribe().getPicklistValues();
    public static Final String DRAFT_ORDER_STATUS = 'Draft';
    public static Final String ACTIVATED_ORDER_STATUS = 'Activated';
    public static Final String INVENTORY_ANNOUNCEMENTS = 'Inventory Announcements';
    public static final String ERROR_MESSAGE = 'An error has occurred, please take a screenshot with the URL and send it to IT.';
    public static final String STANDARD_PRICEBOOK_ID = '01s10000001Uv7q';
}